---
title: "An overview of lax"
author: "Paul Northrop"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{An overview of lax}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: lax.bib
---

```{r, include = FALSE}
knitr::opts_chunk$set(comment = "#>", collapse = TRUE)
```

The *lax* package

evd* [@evd], *evir* [@evir], *extRemes* [@extRemes], *fExtremes* [@fExtremes], *ismev* [@ismev] and *texmex* [@texmex].

```{r}
library(lax)
library(evd)
# An example from the evd::fgev documentation
set.seed(4082019)
uvdata <- evd::rgev(100, loc = 0.13, scale = 1.1, shape = 0.2)
M0 <- evd::fgev(uvdata)
M1 <- evd::fgev(uvdata, nsloc = (-49:50)/100)
adj0 <- alogLik(M0)
adj1 <- alogLik(M1)
summary(adj1)
```

Features provided by *chandwich*

## Confidence intervals

```{r}
confint(adj1)
```

## Confidence regions

## Adjusted likelihood ratio tests

```{r}
anova(adj1, adj0)
```


## References

<script type="text/x-mathjax-config">
   MathJax.Hub.Config({  "HTML-CSS": { minScaleAdjust: 125, availableFonts: [] }  });
</script>

